export default {
    JSE001 : 'Please fill %s!',
	JSE002 : 'Please choose %s!',
	JSE003 : 'Please fill %s in English Character and Number Only !',
	JSE004 : 'Please select %s!',
	JSE005 : 'Please fill %s in English Number Only!',
	JSE006 : '%s is already exists!',
	JSE007 : '%s must be less than %s!',
	JSE008 : '%s is invalid!',
	JSE009 : 'Password and Confirm Password do not match!',
	JSE010 : 'Data is not found!',
	JSE011 : 'Please select at least %s!',
	JSE012 : 'Please fill %s between %s and %s numbers!',
	JSE013 : '%s is allow number and decimal!',
	JSE014 : '%s is maximum allow %s digits!',
	JSE015 : '%s is allow character, number, space, dash and underscore!',
	JSE016 : '%s is allow character, number and underscore!',
	JSE017 : '%s is not an image file!',
	JSE018 : 'Password must be contained capital letter, small letter, special characters and numbers!',
	JSE019 : '%s must be include 8 characters!',
	JSE020 : '%s must be select!',
	JSE021 : '%s is greater than %s!',
  };
