export default {
    // JSE001 : 'Please select %s!',
    // JSE002 : '%s is greater than %s!',

    // /* For Employee Overtime Rate List Start */
    // JSE003 : 'Delete Successfully!',
    // JSE004 : 'Please choose you want to Delete!',
    // /* For Employee Overtime Rate List End */
    // JSE10083 : 'The %s field is required.',

    // /*BRC VN coppy Message from cake project*/
    // JSE005 : 'Please fill %s  English Number Only!',
    // JSE006 : '%s is already exists!',
    // JSE007 : '%s is less than %s!',
    // JSE008 : '%s is much than %s!',
    // JSE009 : '%s is invalid!',
    // JSE010 : '%s is greater than %s!',
    // JSE011 : 'Please choose %s only!',
    // JSE012 : 'Please fill %s is single byte character Only!',
    // JSE014 : 'Date excceds from current date.Please choose %s again!',
    // JSE015 : 'Are you sure want to delete?',
    // JSE016 : '%s must be less than %s!',
    // JSE017 : 'Please fill Password at least 6 characters!',
    // JSE018 : 'Please fill %s Positive Number Only!',
    // JSE019 : 'Please Choose Upload File!',
    // JSE020 : 'Cannot Upload Photo!',
    // JSE021 : 'Do you want to Overwrite this file?',
    // JSE022 : 'Please wait until the loading complete!',
    // JSE023 : 'Please check of your Working Day And Time!',
    // JSE024 : '%s must be Sunday of the week!',
    // JSE025 : '%s must be Saturday of the week!',
    // JSE026 : '%s is not accept zero!',
    // JSE027 : 'Please fill %s is between 0 to 1!',
    // JSE028 : '%s and %s is not match!',
    // JSE029 : 'Please choose first day of the month!',
    // JSE030 : 'Please choose last day of the month!',
    // JSE031 : 'Date range must not exceed 30 days!',
    // JSE032 : '%s is not Zero',
    // JSE033 : 'Upload File Error.!',
    // JSE034 : 'This month is not calculate salary.',
    // JSE037 : 'Invalid File Format!',
    // JSE038 : 'Uploaded File size must be less than 2MB!',
    // JSE041 : 'Upload Success!',
    // JSE042 : 'Upload Fail!',
    // JSE045 : 'Are you sure want to save?</br>After click OK button, you cannot edit anything!',
    // JSE046 : 'Are you sure want to receive?',
    // JSE047 : 'Please choose Leave Date again! This Date is not include in shift assign date.',
    // JSE048 : 'Are you sure want to edit?',
    // JSE053 : 'Please fill Employee Id %s of  %s is English Number Only!',
    // JSE054 : 'Please fill Employee Id %s of  %s !',
    // JSE055 : 'Please add the family member!',
    // JSE056 : 'Please check Employee Checkbox!',
    // JSE057 : 'Shift Assign Date is already exist.We delete the shift assign date that already exist shift assign date! ',
    // JSE058 : 'Shift Assign Date is already exist!',
    // JSE059 : '%s is between 1 to 31!',
    // JSE060 : 'This leave type of remain leave does not exit.',
    // JSE061 : 'Please choose %s!Remain leave is not insufficient for this leave Time.',
    // JSE062 : 'Please choose %s!Remain leave is equal to zero.',
    // JSE063 : 'From Date must be 26.',
    // JSE064 : 'To Date must be 25.',
    // JSE065 : 'Are you sure want to confirm?</br>After click OK button, you cannot edit anything!',
    // JSE066 : 'Are you sure want to denied?</br>After click OK button, you cannot edit anything!',
    // JSE067 : 'This %s does not exit in your team!',
    // JSE068 : '%s is successful.',
    // JSE069 : 'Data is not found.',
    // JSE075 : 'Are you sure want to reset Password?',

    // // nayzaw ( MRBS booking)
    // JSE080 : 'Please Select User.',
    // JSE081 : 'Booking end time must be greater than start time.',
    // JSE082 : 'Please choose by click on Employee or Guest button.',
    // // MNDM (MRBS booking)
    // JSE083 : 'Please choose date.',
    // JSE084 : 'Your selected date is passed over.',
    // JSE085 : 'Please choose time.',
    // JSE086 : 'Please choose correct time.',
    // JSE087 : 'Please select time completely.',
    // JSE088 : 'Your selected time is passed over.',
    // // nayzaw
    // JSE089 : 'Please select end time.',
    // JSE090 : 'Please choose room.',
    // JSE091 : 'Plese select detail date (eg. daily).',
    // JSE092 : 'Booking successful. The number of booked days are %s days. Do you want to invite?',
    // JSE093 : 'Booking date is empty between chosen two dates.',
    // // MNDM
    // JSE094 : 'Please choose different time of existing end-time.',

    // // nayzaw
    // JSE095 : 'Multiple space does not allowed!',
    // JSE096 : 'Only space does not allowed!',
    // // MTC
    // JSE097 : 'Do you want to invite?',
    // //MNDM
    // JSE098 : 'Your booking room is starting .It cannot be deleted.',
    // JSE099 : 'Please choose from time.',

    // //lynn hteain oo(exchange date )
    // JSE076 : 'There is no employee data to save.',
    // JSE077 : 'Regular Attendance Date should not be same with Exchange Date.',
    // JSE078 : 'Duplicate Regular Attendance Date',
    // JSE079 : 'Duplicate Exchange Date',
    // JSE100 : 'Are you sure you want to save?',
    // JSE101 : 'This month is already calculated salary!',
    // JSE102 : 'There is requested data for business trip entry.',
    // JSE103 : 'Cannot exchange when leave data is exist.', //nayzaw
    // JSE104 : "Cannot exchange when overtime data is exist.", //nayzaw
    // JSE105 : "No Shift Assign Days !!!",
    // JSE106 : "There is already data about exchange date.",
    // JSE107 : "Regular Attendance Dates are already saved as Exchange dates.",
    // JSE109 : 'There is requested data for overtime.',

    // //lynn hteain oo(log history search)
    // JSE108: "Please select the form name.",
    // JSE109 : "%s is over %s characters.", // TTN

    // JSE110 : "Allowed only 'jpeg' and 'pdf'", //nayzaw
    // JSE111 : "File size is limited to 10 Megabytes(MB)", //nayzaw
    // JSE109 : "Some employee of Overtime Setting is already exist.Are you sure you want to overwrite?", // SWT

    // // nayzaw [ JSE112 to JSE114 ]
    // JSE113 : "Regular Attendance Date must not be same with Exchange Date",
    // JSE114 : "Shift only can't be exchanged without shift assign",
    // JSE115 : "Must be included at least one shift",
    // JSE116 : 'Upload File Name is limited to 40 characters.', //MTC for Emp Guide Rule

    // JSE112 : 'Your selected leave is not allowed for single and divorce.', //MTC
    // JSE113 : 'Bonus Data is not found.', //CZT
    // JSE117 : 'Are you sure want to delete?</br>After click OK button, your salary transfer setting does not exist!',  //CZT
    // JSE118 : 'This leave type will count holidays between leave dates.</br> Are you sure want to confirm?',//AyeSu for leaverequest form
    // JSE119 : 'Please upload the file without special characters!',//AyeSu for guiderule reg form
    // JSE120 : 'Please fill %s between Positive Number 2 points and Positive Decimal 2 points!', // CZT for OT Rate
    // /*end BRC VN coppy Message from cake project*/

    // /*error comon BVN created */
    // JSE10000 : 'Invalid Number!',
    // JSE10043 : 'The %s must be greater than 0.',
    // JSE10059 : 'The Fixed Amount must be less than 300000.',
    // JSE10079 : 'The %s must be a number.',      
    // JSE10010 : '%s is required!',
    // /*end error comon BVN created */
    // JSE001:'Please select %s!',
    // JSE002:'%s is greater than %s!',
    // JSE003:'Delete Successfully!',
    // JSE004:'Please choose you want to Delete!',
    // JSE005:'Please fill %s  English Number Only!',
    // JSE006:'%s is already exists!',
    // JSE007:'%s is less than %s!',
    // JSE008:'%s is much than %s!',
    // JSE009:'%s is invalid!',
    // JSE010:'%s is greater than %s!',
    // JSE011:'Please choose %s only!',
    // JSE012:'Please fill %s is single byte character Only!',
    // JSE014:'Date excceds from current date.Please choose %s again!',
    // JSE015:'Are you sure want to delete?',
    // JSE016:'%s must be less than %s!',
    // JSE017:'Please fill Password at least 6 characters!',
    // JSE018:'Please fill %s Positive Number Only!',
    // JSE019:'Please Choose Upload File!',
    // JSE020:'Cannot Upload Photo!',
    // JSE021:'Do you want to Overwrite this file?',
    // JSE022:'Please wait until the loading complete!',
    // JSE023:'Please check of your Working Day And Time!',
    // JSE024:'%s must be Sunday of the week!',
    // JSE025:'%s must be Saturday of the week!',
    // JSE026:'%s is not accept zero!',
    // JSE027:'Please fill %s is between 0 to 1!',
    // JSE028:'%s and %s is not match!',
    // JSE029:'Please choose first day of the month!',
    // JSE030:'Please choose last day of the month!',
    // JSE031:'Date range must not exceed 30 days!',
    // JSE032:'%s is not Zero',
    // JSE033:'Upload File Error.!',
    // JSE034:'This month is not calculate salary.',
    // JSE037:'Invalid File Format!',
    // JSE038:'Uploaded File size must be less than 2MB!',
    // JSE041:'Upload Success!',
    // JSE042:'Upload Fail!',
    // JSE045:'Are you sure want to save?</br>After click OK button, you cannot edit anything!',
    // JSE046:'Are you sure want to receive?',
    // JSE047:'Please choose Leave Date again! This Date is not include in shift assign date.',
    // JSE048:'Are you sure want to edit?',
    // JSE053:'Please fill Employee Id %s of  %s is English Number Only!',
    // JSE054:'Please fill Employee Id %s of  %s !',
    // JSE055:'Please add the family member!',
    // JSE056:'Please check Employee Checkbox!',
    // JSE057:'Shift Assign Date is already exist.We delete the shift assign date that already exist shift assign date! ',
    // JSE058:'Shift Assign Date is already exist!',
    // JSE059:'%s is between 1 to 31!',
    // JSE060:'This leave type of remain leave does not exit.',
    // JSE061:'Please choose %s!Remain leave is not insufficient for this leave Time.',
    // JSE062:'Please choose %s!Remain leave is equal to zero.',
    // JSE063:'From Date must be 26.',
    // JSE064:'To Date must be 25.',
    // JSE065:'Are you sure want to confirm?</br>After click OK button, you cannot edit anything!',
    // JSE066:'Are you sure want to denied?</br>After click OK button, you cannot edit anything!',
    // JSE067:'This %s does not exit in your team!',
    // JSE068:'%s is successful.',
    // JSE069:'Data is not found.',
    // JSE075:'Are you sure want to reset Password?',
    // JSE080:'Please Select User.',
    // JSE081:'Booking end time must be greater than start time.',
    // JSE082:'Please choose by click on Employee or Guest button.',
    // JSE083:'Please choose date.',
    // JSE084:'Your selected date is passed over.',
    // JSE085:'Please choose time.',
    // JSE086:'Please choose correct time.',
    // JSE087:'Please select time completely.',
    // JSE088:'Your selected time is passed over.',
    // JSE089:'Please select end time.',
    // JSE090:'Please choose room.',
    // JSE091:'Plese select detail date (eg. daily).',
    // JSE092:'Booking successful. The number of booked days are %s days. Do you want to invite?',
    // JSE093:'Booking date is empty between chosen two dates.',
    // JSE094:'Please choose different time of existing end-time.',
    // JSE095:'Multiple space does not allowed!',
    // JSE096:'Only space does not allowed!',
    // JSE097:'Do you want to invite?',
    // JSE098:'Your booking room is starting .It cannot be deleted.',
    // JSE099:'Please choose from time.',
    // JSE076:'There is no employee data to save.',
    // JSE077:'Regular Attendance Date should not be same with Exchange Date.',
    // JSE078:'Duplicate Regular Attendance Date',
    // JSE079:'Duplicate Exchange Date',
    // JSE100:'Are you sure you want to save?',
    // JSE101:'This month is already calculated salary!',
    // JSE102:'There is requested data for business trip entry.',
    // JSE103:'Cannot exchange when leave data is exist.',
    // JSE104:'Cannot exchange when overtime data is exist.',
    // JSE105:'No Shift Assign Days !!!',
    // JSE106:'There is already data about exchange date.',
    // JSE107:'Regular Attendance Dates are already saved as Exchange dates.',
    // JSE109:'There is requested data for overtime.',
    // JSE108:'Please select the form name.',
    // JSE110:'Allowed only "jpeg" and "pdf"',
    // JSE111:'File size is limited to 10 Megabytes(MB)',
    // JSE113:'Regular Attendance Date must not be same with Exchange Date',
    // JSE114:'Shift only cant be exchanged without shift assign',
    // JSE115:'Must be included at least one shift',
    // JSE116:'Upload File Name is limited to 40 characters.',
    // JSE112:'Your selected leave is not allowed for single and divorce.',
    // JSE117:'Are you sure want to delete?</br>After click OK button, your salary transfer setting does not exist!',
    // JSE118:'This leave type will count holidays between leave dates.</br> Are you sure want to confirm?',
    // JSE119:'Please upload the file without special characters!',
    // JSE120:'Please fill %s between Positive Number 2 points and Positive Decimal 2 points!',
    // JSE121:'Bonus Data is not found.',
    // JSE122:'Some employee of Overtime Setting is already exist.Are you sure you want to overwrite?',
    // JSE123:'%s is over %s characters.',
    // JSE10000:'Invalid Number!',
    // JSE10043:'The %s must be greater than 0.',
    // JSE10059:'The Fixed Amount must be less than 300000.',
    // JSE10079:'The %s must be a number.',
    // JSE10010:'%s is required!',
    // JSE10020:'Total of %s must be 100%!',
    // JSE128 : "%s is over %s digits!",
    // JSE132:'Please edit %s first!'
  };
