export default {
    JSE001 : 'Please select %s!',
    JSE002 : '%s is greater than %s!',
    JSE003 : 'Delete Successfully!',
    JSE004 : 'Please choose you want to Delete!',
    JSE005 : 'Please fill %s!',
    JSE006 : 'Please fill %s of following employee!.<br/>Employee ID :',
    JSE007 : '%s is already exists!',
    JSE008 : 'There is a mismatch between applicants and selected employees!',
    JSE009 : 'The number of files has exceeded.Maximum upload files limit is 20!',
    JSE010 : 'Please fill Leave Name English Character Only!',
    JSE011 : '%s is greater than 100!',
    JSE012 : 'Please fill %s is between 0 to 1!',
    JSE013 : 'Please fill %s English Number Only!',
    JSE014 : '%s is greater than %s!',
    JSE015 : '%s is greater than 60 minutes!',
    JSE016 : 'Please fill %s Positive Number Only!',
    JSE017 : '%s is less than %s!',
    JSE018 : 'Please fill %s!',
    JSE019 : 'Please choose %s!',
    JSE020 : 'Please choose %s Only!',
    JSE021 : 'Please choose you want to Delete!',
    JSE022 : 'Duplicate files are not allowed!'
};
